// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXq6BDMokm3zj-C7uk9rYekC6Y71glT6I',
    appId: '1:897224526421:web:a12ddd069cfa739fe722dc',
    messagingSenderId: '897224526421',
    projectId: 'uaskelompok2-d6407',
    authDomain: 'uaskelompok2-d6407.firebaseapp.com',
    storageBucket: 'uaskelompok2-d6407.firebasestorage.app',
    measurementId: 'G-XDF9HC9HPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYj_hpfed-QHURcXcx7R2rQAak6ofRDzc',
    appId: '1:897224526421:android:a2bccffa94e5914ee722dc',
    messagingSenderId: '897224526421',
    projectId: 'uaskelompok2-d6407',
    storageBucket: 'uaskelompok2-d6407.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlW9-bw_YEn2e1AiRI4Wf5Wmzjmh31ToA',
    appId: '1:897224526421:ios:7c97eeaf0503d27ae722dc',
    messagingSenderId: '897224526421',
    projectId: 'uaskelompok2-d6407',
    storageBucket: 'uaskelompok2-d6407.firebasestorage.app',
    iosBundleId: 'com.example.projekUasKel2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXq6BDMokm3zj-C7uk9rYekC6Y71glT6I',
    appId: '1:897224526421:web:6486143750f562cfe722dc',
    messagingSenderId: '897224526421',
    projectId: 'uaskelompok2-d6407',
    authDomain: 'uaskelompok2-d6407.firebaseapp.com',
    storageBucket: 'uaskelompok2-d6407.firebasestorage.app',
    measurementId: 'G-K9WSD1DVHH',
  );
}
